# Generated by Django 6.0.5 on 2026-06-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='model_provider',
            field=models.CharField(default='gigachat', max_length=50),
        ),
    ]
